### ISSUE TITLE
Corner case: won but then immediately wiped out by a catastrophe

### ISSUE THREAD

**Issue by patrakov** [Frunit/qpop.js#2]
I did not have this situation, but the code seemingly does not handle a triple-coincidence (just eliminated the other remaining species on the world map, then a catastrophe wiped out all my human-controlled survivors, and that was the last turn) well. Could you please double-check?

**Comment by Frunit** [comment]
Ah, tricky to test! But I think it should be caught here (and the following lines):
https://github.com/Frunit/qpop.js/blob/4d2844f834cb9ddd874929d7c2f10f53e0ed1ebc/src/game.js#L374

I will try to test this, though.

**Comment by Frunit** [comment]
Wasn't that difficult at all. I just hardcoded the catastrophe to be "flood", placed one own and one enemy unit close to the shore, fought the enemy (died out) and then clicked next. My single unit dies, I get the message "sorry, but you died". The map is still shown. I click next and the losing end screen appears. Looks like it works, but I never checked that, so good you mentioned it!
