### ISSUE TITLE
If the player eliminates others quickly in a 20-step game, he is forced to continue alone

### ISSUE THREAD

**Issue by patrakov** [Frunit/qpop.js#3]
To reproduce:

1. Set the game length to 20 steps.
2. Eliminate all other players within, say, 15 moves.

Expected result (based on common sense, I do not have the original game): "do you want to continue alone?"
Actual result: the game forces me to continue alone for the remaining 5 steps.

Please close as a non-bug if the same issue exists in the original.

**Comment by Frunit** [comment]
You are right. For some reason, I explicitly programmed the game to automatically continue if the number of turns is not set to "unlimited". I just tested the behaviour of the original game and it actually asks if I want to continue or not.
Fixed with commit b8a7be9.
